export const NAV_LINKS = [
  { id: "Home", labelKey: "navHome" },
  { id: "About", labelKey: "navAbout" },
  { id: "Experience", labelKey: "navExperience" },
  { id: "Skills", labelKey: "navSkills" },
  { id: "Projects", labelKey: "navProjects" },
  { id: "Contact", labelKey: "navContact" }
];

export const SKILLS = [
  // BACKEND / LANGUAGES
  { name: "Python", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/python/python-original.svg", level: 82, category: "backend", color: "#ca8a04" },

  // FRONTEND
  { name: "HTML5", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg", level: 90, category: "frontend", color: "#e34f26" },
  { name: "CSS", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg", level: 88, category: "frontend", color: "#1572b6" },
  { name: "JavaScript", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg", level: 85, category: "frontend", color: "#f7df1e" },
  { name: "React", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/react/react-original.svg", level: 78, category: "frontend", color: "#06b6d4" },
  { name: "Figma", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg", level: 75, category: "frontend", color: "#F24E1E" },

  // BACKEND / LANG & FRAMEWORK RELATIONS
  { name: "Java", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original.svg", level: 85, category: "backend", color: "#e11d48" },
  { name: "Spring Boot", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/spring/spring-original.svg", level: 88, category: "backend", color: "#16a34a" },
  { name: "REST API", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/openapi/openapi-original.svg", level: 85, category: "backend", color: "#6BA539" },
  { name: "PHP", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg", level: 80, category: "backend", color: "#4f46e5" },

  // ORM / DATABASE
  { name: "JPA / Hibernate", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/hibernate/hibernate-original.svg", level: 80, category: "backend", color: "#2563eb" },
  { name: "MySQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original.svg", level: 85, category: "backend", color: "#0284c7" },
  { name: "PostgreSQL", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postgresql/postgresql-original.svg", level: 75, category: "backend", color: "#334155" },
  { name: "SQL Server", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/microsoftsqlserver/microsoftsqlserver-original.svg", level: 80, category: "backend", color: "#CC292B" },

  // TOOLS / QA
  { name: "JUnit", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/junit/junit-original.svg", level: 76, category: ["tools", "qa"], color: "#db2777" },
  { name: "Postman", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/postman/postman-original.svg", level: 82, category: ["tools", "qa"], color: "#FF6C37" },
  { name: "GitHub", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original.svg", level: 88, category: "tools", color: "#181717" },
  { name: "VS Code", icon: "https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vscode/vscode-original.svg", level: 85, category: "tools", color: "#007ACC" },
  { name: "Manual Testing", icon: "🔍", level: 82, category: ["tools", "qa"], color: "#475569" },
];

export const PROJECTS = [
  {
    title: "Mobile Phone Store",
    subtitle: "Full-Stack · Management System",
    periodKey: "storePeriod",
    descKey: "storeDesc",
    tags: ["PHP", "MySQL", "JavaScript", "JUnit", "Manual Testing"],
    highlightKey: "storeHighlight",
    github: "https://github.com/VThuongg/Mobile-Phone-Store",
    demo: "#",
    category: "web",
    image: "/avt_prj_phone.png"
  },
  {
    title: "Secure Email Encryption",
    subtitle: "Hybrid Cryptography · Web App",
    periodKey: "emailPeriod",
    descKey: "emailDesc",
    tags: ["Flask", "Python", "PyCryptodome"],
    highlightKey: "emailHighlight",
    github: "https://github.com/VThuongg/Secure-Email-Encryption",
    demo: "https://secure-email-encryption.onrender.com/",
    category: "web",
    image: "/avt_prj_email.png"
  },
  {
    title: "ProtGO",
    subtitle: "Data Pipeline · Classification Model",
    periodKey: "protgoPeriod",
    descKey: "protgoDesc",
    tags: ["Python", "PyTorch", "HuggingFace", "XGBoost", "Scikit-learn"],
    highlight: "Fmax 0.747 · AuPRC 0.785",
    github: "https://github.com/VThuongg/protgo",
    demo: null,
    category: "ai",
    image: "/protGO.png"
  },
  {
    title: "MovieLens Analysis",
    subtitle: "Data Science · Audience Satisfaction",
    periodKey: "movielensPeriod",
    descKey: "movielensDesc",
    tags: ["Python", "Pandas", "XGBoost", "Matplotlib", "Seaborn"],
    highlightKey: "movielensHighlight",
    github: "https://github.com/VThuongg/Movie-Audience-Satisfaction-Analysis",
    demo: null,
    category: "ai",
    image: "/images/projects/movielens.png"
  },
];

export const TIMELINE = [
  {
    year: "2026",
    titleKey: "timeline2026Title",
    descKey: "timeline2026Desc"
  },
  {
    year: "2025",
    titleKey: "timeline2025Title",
    descKey: "timeline2025Desc"
  },
  {
    year: "2024",
    titleKey: "timeline2024Title",
    descKey: "timeline2024Desc"
  },
  {
    year: "2022",
    titleKey: "timeline2022Title",
    descKey: "timeline2022Desc"
  }
];

export const TRANSLATIONS = {
  en: {
    logoText: "VThuongg",
    navHome: "Home",
    navAbout: "About",
    navExperience: "Experience",
    navSkills: "Skills",
    navProjects: "Projects",
    navContact: "Contact",
    hireMe: "Hire Me",
    heroSubtitle: "WELCOME TO MY PORTFOLIO",
    heroAvatarTitle: "Information Systems Student",
    bioRole: "Information Systems Student",
    heroTitlePrefix: "Hi, I'm",
    heroDesc: "Building scalable systems from backend to browser. Turning data into insight, code into real-world impact.",
    viewProjects: "View Projects →",
    downloadCV: "↓ Download CV",
    statProjectsVal: "3+",
    statProjectsLabel: "Projects",
    statEduVal: "SGU",
    statEduLabel: "Education",
    statLocVal: "HCM City",
    statLocLabel: "Vietnam 🇻🇳",
    aboutLabel: "ABOUT ME",
    aboutTitle1: "Code with purpose,",
    aboutTitle2: "ship with care.",
    aboutDesc1: "I am an Information Systems student at Sai Gon University (SGU), specializing in full-stack development with a strong focus on React, Next.js, and FastAPI. I combine robust software design, quality-driven testing, and logic-based problem solving to deliver sophisticated and scalable digital solutions.",
    aboutDesc2: "Recently, I completed a 3-month Game Development Internship at ASOL (Alpaca Solutions). Currently, I am focused on building a comprehensive Food Ordering Platform using FastAPI and Supabase, with an aspiration to evolve into a Technical Lead within the next five years.",
    tabStory: "My Story",
    tabValues: "My Values",
    valuesTitle: "Core Values & Principles",
    value1Title: "Quality & Clean Code",
    value1Desc: "Code is read more than it is written. I strive for readability, maintainability, and clean architecture.",
    value2Title: "Continuous Learning",
    value2Desc: "The tech landscape is always evolving. I dedicate time each week to learn new technologies and tools.",
    value3Title: "Problem Solving",
    value3Desc: "Using analytical thinking and data science to tackle complex bioinformatic and business problems.",
    journeyTitle: "My Journey",
    skillsLabel: "WHAT I DO BEST",
    skillsTitle: "My Skills",
    skillsDesc: "A comprehensive overview of my technical skills and expertise",
    filterAll: "All",
    filterFrontend: "Frontend",
    filterBackend: "Backend",
    filterQA: "Testing & QA",
    filterTools: "Tools",
    projectsLabel: "MY WORK",
    projectsTitle: "Featured Projects",
    projectsDesc: "A selection of projects I've worked on, showcasing my skills and expertise",
    projFilterAll: "All Projects",
    projFilterAI: "Research & AI",
    projFilterWeb: "Web Apps",
    badgeAI: "Research",
    badgeWeb: "Web App",
    contactLabel: "GET IN TOUCH",
    contactTitle: "Let's work together",
    contactDesc: "Open to full-time opportunities, freelance projects, or just a good tech conversation.",
    contactCopyEmail: "Copy Email",
    contactCopied: "Copied!",
    contactNamePlaceholder: "Your Name",
    contactEmailPlaceholder: "Your Email",
    contactMessagePlaceholder: "Your Message",
    contactSendBtn: "Send Message",
    contactSendingBtn: "Sending...",
    contactSuccessMsg: "Thank you! Your message has been sent successfully.",
    contactErrorMsg: "Oops! Something went wrong, please try again.",
    footerText: "Designed & Built by Vo Thi Thuong",
    ownerName: "Vo Thi Thuong",
    
    // Project Specific Translations
    protgoPeriod: "Jan 2026 – May 2026",
    protgoDesc: "Multi-expert data processing pipeline and model evaluation system for automated protein function classification. Optimized network efficiency to reduce parameters by 96%.",
    storePeriod: "Jan 2025 – May 2025 · Team of 4",
    storeDesc: "Full-stack web app for managing products, customers, employees & orders with role-based access control and comprehensive QA testing.",
    storeHighlight: "Role-Based Access Control",
    movielensPeriod: "2025 · Team of 3",
    movielensDesc: "Data-driven analysis and pipeline engineering of movie ratings. Developed statistical modeling and feature analysis pipelines using Python.",
    movielensHighlight: "Director Power 2.5× > Actor",
    emailPeriod: "Sep 2024 – Dec 2024",
    emailDesc: "Architected and developed a secure email application implementing hybrid cryptography (RSA-2048 + AES-256) to protect confidential communications and file attachments with end-to-end encryption.",
    emailHighlight: "Hybrid Cryptography (RSA + AES)",

    // Experience Section Translations
    experienceLabel: "WORK & INTERNSHIPS",
    experienceTitle: "Professional Experience",
    experienceDesc: "A timeline of my internships and work experience in software development.",
    expTypeIntern: "Internship",
    expTypeWork: "Part-time / Work",
    expASOLRole: "Game Development Intern",
    expASOLDesc: "3-month internship at ASOL (Alpaca Solutions)",
    expASOLPoint1: "Contributed to casual game development and engine building projects at a professional game studio.",
    expASOLPoint2: "Collaborated on designing and developing game engines to support multiple similar casual game architectures.",
    expASOLPoint3: "Implemented core gameplay mechanics, optimized system performance, and built responsive user interfaces.",
    expMindXRole: "Programming Teaching Assistant",
    expMindXDesc: "Teaching assistant at MindX Technology School",
    expMindXPoint1: "Assisted in delivering programming and game development courses (Scratch, GameMaker, Python, HTML/CSS/JS) to students.",
    expMindXPoint2: "Guided students in understanding game design logic, building interactive gameplay mechanics, and debugging game code.",
    expMindXPoint3: "Facilitated practice sessions and mentored students in completing their final game and web application projects.",

    // Timeline Translations
    timelineASOLTitle: "Game Development Intern",
    timelineASOLDesc: "Completed a 3-month internship at ASOL (Alpaca Solutions), a game studio specializing in casual games. Developed game applications and designed reusable engines for similar game projects.",
    timeline2026Title: "Game Development & QA Testing",
    timeline2026Desc: "Completed a 3-month game development internship at ASOL. Designed reusable game engines and developed automated and manual QA testing methodologies for software projects.",
    timeline2025Title: "Full-Stack Web & Database Systems",
    timeline2025Desc: "Developed full-stack web applications, designed relational databases, authored JUnit test cases, and conducted QA testing processes.",
    timeline2024Title: "Foundational IT Knowledge",
    timeline2024Desc: "Focused on learning core computer science concepts, software fundamentals, and built initial basic projects.",
    timeline2022Title: "Started IT Journey",
    timeline2022Desc: "Entered university, laying strong foundations in computer science, software engineering, and software quality assurance."
  },
  vi: {
    logoText: "Võ Thương",
    navHome: "Trang chủ",
    navAbout: "Giới thiệu",
    navExperience: "Kinh nghiệm",
    navSkills: "Kỹ năng",
    navProjects: "Dự án",
    navContact: "Liên hệ",
    hireMe: "Liên hệ ngay",
    heroSubtitle: "CHÀO MỪNG ĐẾN VỚI PORTFOLIO CỦA MÌNH",
    heroAvatarTitle: "Sinh viên Hệ thống thông tin",
    bioRole: "Sinh viên Hệ thống thông tin",
    heroTitlePrefix: "Xin chào, mình là",
    heroDesc: "Xây dựng các hệ thống mở rộng từ backend đến giao diện người dùng. Chuyển đổi dữ liệu thành thông tin hữu ích và lập trình tạo ra giá trị thực tiễn.",
    viewProjects: "Xem dự án →",
    downloadCV: "↓ Tải CV",
    statProjectsVal: "3+",
    statProjectsLabel: "Dự án",
    statEduVal: "SGU",
    statEduLabel: "Học vấn",
    statLocVal: "TP. Hồ Chí Minh",
    statLocLabel: "Việt Nam 🇻🇳",
    aboutLabel: "GIỚI THIỆU",
    aboutTitle1: "Lập trình có mục đích,",
    aboutTitle2: "sản phẩm có chất lượng.",
    aboutDesc1: "Mình là sinh viên ngành Hệ thống Thông tin tại Trường Đại học Sài Gòn (SGU), hướng tới phát triển Full-Stack với thế mạnh về React, Next.js và FastAPI. Mình tập trung xây dựng phần mềm chất lượng, kiểm thử hệ thống (Manual & Automated Testing) và áp dụng tư duy logic trong phát triển game.",
    aboutDesc2: "Vừa qua, mình đã hoàn thành kỳ thực tập 3 tháng ở vị trí Phát triển Game tại ASOL (Alpaca Solutions). Hiện tại, mình đang tập trung xây dựng nền tảng Gọi món ăn trực tuyến (Food Ordering Platform) kết hợp FastAPI và Supabase, hướng tới mục tiêu phát triển thành một Technical Lead chuyên nghiệp.",
    tabStory: "Câu chuyện",
    tabValues: "Giá trị cốt lõi",
    valuesTitle: "Giá trị cốt lõi & Nguyên tắc",
    value1Title: "Chất lượng & Code sạch",
    value1Desc: "Code được đọc nhiều hơn được viết. Mình luôn hướng tới sự mạch lạc, dễ bảo trì và kiến trúc chuẩn chỉ.",
    value2Title: "Học hỏi không ngừng",
    value2Desc: "Thế giới công nghệ luôn vận động. Mình dành thời gian hàng tuần để nghiên cứu các công nghệ mới và nâng cao năng lực.",
    value3Title: "Giải quyết vấn đề",
    value3Desc: "Ứng dụng tư duy phân tích và khoa học dữ liệu nhằm giải quyết các vấn đề phức tạp trong tin sinh học và kinh doanh.",
    journeyTitle: "Hành trình sự nghiệp",
    skillsLabel: "THẾ MẠNH CỦA MÌNH",
    skillsTitle: "Kỹ năng của mình",
    skillsDesc: "Tổng quan toàn diện về các kỹ năng kỹ thuật và năng lực chuyên môn của mình",
    filterAll: "Tất cả",
    filterFrontend: "Frontend",
    filterBackend: "Backend",
    filterQA: "Kiểm thử & QA",
    filterTools: "Công cụ",
    projectsLabel: "SẢN PHẨM",
    projectsTitle: "Dự án tiêu biểu",
    projectsDesc: "Một số dự án tiêu biểu mà mình từng phát triển, thể hiện năng lực và tư duy lập trình",
    projFilterAll: "Tất cả dự án",
    projFilterAI: "Nghiên cứu & AI",
    projFilterWeb: "Web Apps",
    badgeAI: "Nghiên cứu",
    badgeWeb: "Web App",
    contactLabel: "KẾT NỐI",
    contactTitle: "Cùng làm việc nhé",
    contactDesc: "Sẵn sàng đón nhận cơ hội làm việc toàn thời gian, dự án freelance hoặc đơn giản là một buổi trao đổi về công nghệ.",
    contactCopyEmail: "Sao chép Email",
    contactCopied: "Đã sao chép!",
    contactNamePlaceholder: "Tên của bạn",
    contactEmailPlaceholder: "Email của bạn",
    contactMessagePlaceholder: "Lời nhắn của bạn",
    contactSendBtn: "Gửi tin nhắn",
    contactSendingBtn: "Đang gửi...",
    contactSuccessMsg: "Cảm ơn bạn! Lời nhắn của bạn đã được gửi đi thành công.",
    contactErrorMsg: "Ối! Đã có lỗi xảy ra, vui lòng thử lại.",
    footerText: "Thiết kế & Lập trình bởi Võ Thị Thương",
    ownerName: "Võ Thị Thương",

    // Project Specific Translations
    protgoPeriod: "Tháng 1/2026 – Tháng 5/2026",
    protgoDesc: "Hệ thống đường ống xử lý dữ liệu và đánh giá mô hình để phân loại tự động chức năng protein. Tối ưu hóa hiệu năng giúp giảm 96% kích thước tham số.",
    storePeriod: "Tháng 1/2025 – Tháng 5/2025 · Nhóm 4 người",
    storeDesc: "Ứng dụng web Full-stack quản lý sản phẩm, khách hàng, nhân viên & đơn hàng với tính năng phân quyền (RBAC) và kiểm thử chất lượng QA toàn diện.",
    storeHighlight: "Phân quyền người dùng (RBAC)",
    movielensPeriod: "2025 · Nhóm 3 người",
    movielensDesc: "Phân tích dữ liệu và kỹ nghệ đường ống dữ liệu xếp hạng phim. Xây dựng các mô hình thống kê và phân tích thuộc tính sử dụng Python.",
    movielensHighlight: "Ảnh hưởng của Đạo diễn > 2.5x Diễn viên",
    emailPeriod: "Tháng 9/2024 – Tháng 12/2024",
    emailDesc: "Thiết kế và phát triển ứng dụng email bảo mật tích hợp mã hóa lai (RSA-2048 + AES-256) nhằm bảo vệ thông tin liên lạc và tệp đính kèm với mã hóa đầu cuối.",
    emailHighlight: "Mã hóa lai RSA-2048 + AES-256",

    // Experience Section Translations
    experienceLabel: "CÔNG VIỆC & THỰC TẬP",
    experienceTitle: "Kinh nghiệm thực tế",
    experienceDesc: "Quá trình thực tập và làm việc trong lĩnh vực phát triển phần mềm.",
    expTypeIntern: "Thực tập",
    expTypeWork: "Công việc",
    expASOLRole: "Thực tập sinh Phát triển Game",
    expASOLDesc: "Kỳ thực tập 3 tháng tại ASOL (Alpaca Solutions)",
    expASOLPoint1: "Tham gia phát triển các dự án game casual và xây dựng game engine tại studio chuyên nghiệp.",
    expASOLPoint2: "Hợp tác thiết kế và phát triển các engine dùng chung cho nhiều dòng game tương tự nhằm tối ưu kiến trúc.",
    expASOLPoint3: "Lập trình cơ chế game cốt lõi, tối ưu hóa hiệu năng hệ thống và xây dựng giao diện người dùng trực quan.",
    expMindXRole: "Trợ giảng Lập trình",
    expMindXDesc: "Trợ giảng tại Trường Công nghệ MindX",
    expMindXPoint1: "Hỗ trợ chuẩn bị giáo án và truyền đạt kiến thức lập trình & phát triển game (Scratch, GameMaker, Python, HTML/CSS/JS) cho học viên.",
    expMindXPoint2: "Hướng dẫn học viên xây dựng logic game, thiết kế cơ chế tương tác và sửa lỗi (debug) mã nguồn game.",
    expMindXPoint3: "Tổ chức các buổi thực hành, review code và đồng hành cùng học viên hoàn thiện các dự án game và website cuối khóa.",

    // Timeline Translations
    timelineASOLTitle: "Thực tập sinh Phát triển Game",
    timelineASOLDesc: "Hoàn thành kỳ thực tập 3 tháng tại ASOL (Alpaca Solutions) - studio chuyên về game casual. Tham gia xây dựng các dự án game và thiết kế engine dùng chung cho các dòng game tương tự.",
    timeline2026Title: "Phát triển Game & Kiểm thử QA",
    timeline2026Desc: "Hoàn thành kỳ thực tập phát triển game tại ASOL. Thiết kế game engine dùng chung và xây dựng các quy trình kiểm thử QA tự động & thủ công cho các dự án phần mềm.",
    timeline2025Title: "Lập trình Web & Hệ thống Cơ sở dữ liệu",
    timeline2025Desc: "Phát triển các ứng dụng web Full-stack, thiết kế cơ sở dữ liệu quan hệ, viết các bộ kiểm thử JUnit và thực hiện các quy trình kiểm thử QA.",
    timeline2024Title: "Kiến thức nền tảng & Dự án cơ bản",
    timeline2024Desc: "Học tập, nắm vững các kiến thức cơ sở ngành và thực hiện các dự án nhỏ, cơ bản để làm quen với lập trình.",
    timeline2022Title: "Bắt đầu con đường CNTT",
    timeline2022Desc: "Nhập học ngành CNTT, xây dựng nền tảng tư duy lập trình vững chắc về cấu trúc dữ liệu, thuật toán, OOP và kiểm thử phần mềm."
  }
};
